# Generated by Django 2.1.4 on 2018-12-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchId', models.AutoField(primary_key=True, serialize=False)),
                ('batchName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BatchPurchaseDetails',
            fields=[
                ('batchPurDetailsId', models.AutoField(primary_key=True, serialize=False)),
                ('serialNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catId', models.AutoField(primary_key=True, serialize=False)),
                ('catName', models.CharField(max_length=150)),
                ('catImg', models.FileField(blank=True, null=True, upload_to='cat_media')),
                ('isDisplay', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('DOJ', models.DateTimeField(auto_now_add=True)),
                ('contactNo', models.CharField(max_length=50)),
                ('contactPerson', models.CharField(max_length=50)),
                ('Logo', models.FileField(blank=True, null=True, upload_to='logo_media')),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pId', models.AutoField(primary_key=True, serialize=False)),
                ('pName', models.CharField(db_index=True, max_length=100)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pimg', models.FileField(blank=True, null=True, upload_to='product_media')),
                ('pdDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purId', models.AutoField(primary_key=True, serialize=False)),
                ('purDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('purDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('purQuantity', models.IntegerField()),
                ('purPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Batch')),
                ('pId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Product')),
                ('purId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Purchase')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subCatId', models.AutoField(primary_key=True, serialize=False)),
                ('subCatName', models.CharField(max_length=150)),
                ('SubCatImg', models.FileField(blank=True, null=True, upload_to='Subcat_media')),
                ('isDisplay', models.BooleanField(default=True)),
                ('catId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supId', models.AutoField(primary_key=True, serialize=False)),
                ('supName', models.CharField(max_length=100)),
                ('supLogo', models.FileField(blank=True, null=True, upload_to='sup_logo')),
                ('supContact1', models.IntegerField()),
                ('supContact2', models.IntegerField()),
                ('supMail', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='supId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='subCatId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.SubCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='supId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Supplier'),
        ),
        migrations.AddField(
            model_name='batchpurchasedetails',
            name='purDetailId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.PurchaseDetail'),
        ),
    ]
