# Generated by Django 2.1.4 on 2019-01-08 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('application', '0002_admin_attributes_productattributes_productimages_sale_saledetail_saledetailbatch_stock_stockdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListings',
            fields=[
                ('plistId', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tId', models.AutoField(primary_key=True, serialize=False)),
                ('s_uId', models.IntegerField()),
                ('b_uId', models.IntegerField()),
                ('tDate', models.DateTimeField(auto_now_add=True)),
                ('tQty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('tdId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uId', models.AutoField(primary_key=True, serialize=False)),
                ('uName', models.CharField(max_length=20)),
                ('is_whole', models.BooleanField()),
                ('is_retail', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='batchpurchasedetails',
            name='purDetailId',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='aID',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='pId',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='pId',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supId',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='batchId',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='pId',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='purId',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='pId',
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='sId',
        ),
        migrations.RemoveField(
            model_name='saledetailbatch',
            name='batchPurDetailsId',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='stockId',
            new_name='stId',
        ),
        migrations.RenameField(
            model_name='stockdetail',
            old_name='sdId',
            new_name='stdId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supId',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='DOS',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='sIn',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='sOut',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='stockId',
        ),
        migrations.AddField(
            model_name='stock',
            name='pId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.Product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='sQty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='pNo',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='stId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Stock'),
        ),
        migrations.AlterField(
            model_name='category',
            name='catName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pName',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subCatName',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Attributes',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='BatchPurchaseDetails',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='ProductAttributes',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseDetail',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleDetail',
        ),
        migrations.DeleteModel(
            name='SaleDetailBatch',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='stdId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.StockDetail'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='tId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Product'),
        ),
        migrations.AddField(
            model_name='productlistings',
            name='pId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Product'),
        ),
        migrations.AddField(
            model_name='productlistings',
            name='uId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Users'),
        ),
        migrations.AddField(
            model_name='stock',
            name='uId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Users'),
        ),
    ]
