# Generated by Django 2.1.4 on 2019-01-08 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('application', '0003_auto_20190108_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='pId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='uId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Users'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='pNo',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='stId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Stock'),
        ),
    ]
