# Generated by Django 2.1.4 on 2019-01-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_users_upass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uPass',
            field=models.CharField(max_length=20),
        ),
    ]
