# Generated by Django 2.1.4 on 2019-01-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20190108_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='pNo',
            field=models.FloatField(),
        ),
    ]
