# Generated by Django 2.1.4 on 2019-01-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20190108_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='pNo',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
