# Generated by Django 2.1.4 on 2019-01-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20190108_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlistings',
            name='pId',
        ),
        migrations.RemoveField(
            model_name='productlistings',
            name='uId',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='pId',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='uId',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='stId',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='pId',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='stdId',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='tId',
        ),
        migrations.DeleteModel(
            name='ProductListings',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockDetail',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionDetail',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
