# Generated by Django 2.1.4 on 2019-01-12 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0013_auto_20190111_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlistings',
            name='uId',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='uId',
        ),
        migrations.AddField(
            model_name='productlistings',
            name='uName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='uName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
