# Generated by Django 2.1.4 on 2019-01-16 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20190112_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuName', models.CharField(max_length=50)),
                ('manuContact', models.IntegerField(blank=True, null=True)),
                ('manuMail', models.CharField(blank=True, max_length=100, null=True)),
                ('manuLogo', models.FileField(blank=True, null=True, upload_to='sup_logo')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='pdDescription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pimg',
        ),
        migrations.AddField(
            model_name='product',
            name='pQty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productlistings',
            name='pdDescription',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productlistings',
            name='pimg',
            field=models.FileField(blank=True, null=True, upload_to='product_media'),
        ),
        migrations.AddField(
            model_name='productlistings',
            name='qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productlistings',
            name='manuName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Manufacturer'),
        ),
    ]
