# Generated by Django 2.1.4 on 2019-01-16 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20190116_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistings',
            name='manuName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Manufacturer'),
        ),
    ]
