# Generated by Django 2.1.4 on 2019-01-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20190116_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistings',
            name='pdDescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
