# Generated by Django 2.1.4 on 2019-01-16 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20190116_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistings',
            name='uName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
