# Generated by Django 2.1.4 on 2019-01-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_auto_20190116_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='manuLogo',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='manuMail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pQty',
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
