# Generated by Django 2.1.4 on 2019-01-16 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20190116_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pId',
        ),
        migrations.AddField(
            model_name='transaction',
            name='pListId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.ProductListings'),
        ),
    ]
