# Generated by Django 2.1.4 on 2019-01-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_auto_20190116_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlistings',
            name='manuName',
        ),
        migrations.RemoveField(
            model_name='productlistings',
            name='pId',
        ),
        migrations.RemoveField(
            model_name='productlistings',
            name='uName',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='pListId',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='pListId',
        ),
        migrations.DeleteModel(
            name='ProductListings',
        ),
    ]
