# Generated by Django 2.1.4 on 2019-01-17 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0023_auto_20190117_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField(null=True)),
                ('pdDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('pimg', models.FileField(blank=True, null=True, upload_to='product_media')),
                ('manuName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Manufacturer')),
                ('pId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Product')),
                ('uName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='pListId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.ProductListings'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pListId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.ProductListings'),
        ),
    ]
