# Generated by Django 2.1.4 on 2019-01-17 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_auto_20190117_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='b_uId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_uId', to=settings.AUTH_USER_MODEL),
        ),
    ]
