# Generated by Django 2.1.4 on 2019-01-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_auto_20190118_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='b_uId',
            field=models.CharField(max_length=50),
        ),
    ]
