# Generated by Django 2.1.4 on 2019-01-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_auto_20190120_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlistings',
            old_name='price',
            new_name='s_price',
        ),
        migrations.AddField(
            model_name='productlistings',
            name='b_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
