# Generated by Django 2.1.4 on 2019-01-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_auto_20190123_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistings',
            name='b_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
