# Generated by Django 2.1.4 on 2019-02-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_auto_20190125_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='catId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subCatId',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
