# Generated by Django 2.1.4 on 2019-02-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_auto_20190227_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catId',
        ),
        migrations.RemoveField(
            model_name='productlistings',
            name='manuName',
        ),
        migrations.RemoveField(
            model_name='productlistings',
            name='pId',
        ),
        migrations.RemoveField(
            model_name='productlistings',
            name='uName',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='pListId',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='uName',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='stId',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='pListId',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='tId',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductListings',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockDetail',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionDetail',
        ),
    ]
