# Generated by Django 2.1.4 on 2019-02-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_auto_20190227_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='SubCatImg',
            new_name='subCatImg',
        ),
    ]
