# Generated by Django 2.1.4 on 2019-02-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_auto_20190227_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='isDisplay',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='isDisplay',
        ),
    ]
