# Generated by Django 2.1.4 on 2019-03-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_auto_20190304_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stock_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
