# Generated by Django 2.1 on 2019-04-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_auto_20190423_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistings',
            name='pimg',
            field=models.FileField(blank=True, default='D:/project/Django1/Project1_trial/media/product_media/default.jpg', null=True, upload_to='product_media'),
        ),
    ]
