# Generated by Django 2.1 on 2019-04-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_auto_20190423_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistings',
            name='pimg',
            field=models.FileField(blank=True, default='product_media/default.jpg', null=True, upload_to='product_media'),
        ),
    ]
